"use client";

import Link from "next/link";
import { useMemo } from "react";
import { useRouter } from "next/navigation";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import {
  ArrowRight, BadgeCheck, Sparkles, ShieldCheck, LayoutDashboard,
  HeartPulse, UserRound, CalendarCheck, ClipboardList, Home, Clock, Stethoscope, Users,
} from "lucide-react";

function InfoCard({ title, description, icon: Icon, delayMs = 0, iconBgClass = "bg-teal-600", tintClass = "from-teal-500/12 via-emerald-500/8 to-transparent" }:{
  title:string; description:string; icon:React.ElementType; delayMs?:number; iconBgClass?:string; tintClass?:string;
}) {
 return <div className="relative overflow-hidden rounded-2xl border border-teal-100 bg-teal-50/60 p-6 shadow-sm transition-transform duration-300 hover:scale-[1.02] hover:shadow-md dark:border-teal-900/40 dark:bg-teal-950/20" style={{animation:`fadeUp 900ms cubic-bezier(0.22,1,0.36,1) ${delayMs}ms both`}}>
  <div className={`pointer-events-none absolute inset-0 bg-gradient-to-br ${tintClass}`} />
  <div className="relative"><div className="flex items-center gap-3"><span className={`inline-flex h-10 w-10 items-center justify-center rounded-xl ${iconBgClass}`}><Icon className="h-5 w-5 text-white"/></span><h3 className="text-base font-semibold text-black dark:text-white">{title}</h3></div><p className="mt-3 text-sm text-zinc-600 dark:text-zinc-400">{description}</p></div>
 </div>
}

export default function NursesPage(){
 const router=useRouter();
 const heroStyle=useMemo(()=>({animation:"fadeUp 900ms cubic-bezier(0.22,1,0.36,1) 0ms both"}),[]);
 const panelStyle=useMemo(()=>({animation:"fadeUp 900ms cubic-bezier(0.22,1,0.36,1) 120ms both"}),[]);
 return <div className="min-h-screen bg-teal-50/40 dark:bg-black"><Header/>
 <style>{`@keyframes fadeUp{from{opacity:0;transform:translateY(32px)}to{opacity:1;transform:translateY(0)}}@keyframes softPulse{0%{transform:scale(1);opacity:.92}50%{transform:scale(1.02);opacity:1}100%{transform:scale(1);opacity:.92}}`}</style>
 <main><section className="relative overflow-hidden border-b border-teal-100 bg-teal-50/70 dark:border-teal-900/40 dark:bg-teal-950/20">
 <div className="pointer-events-none absolute -right-24 -top-24 h-80 w-80 rounded-full bg-teal-500/20 blur-3xl"/><div className="pointer-events-none absolute -bottom-28 -left-28 h-80 w-80 rounded-full bg-emerald-500/20 blur-3xl"/><div className="pointer-events-none absolute left-1/2 top-1/3 h-64 w-64 -translate-x-1/2 rounded-full bg-cyan-500/10 blur-3xl"/>
 <div className="w-full px-4 py-10 sm:px-6 lg:px-10"><div className="grid grid-cols-1 items-center gap-10 lg:grid-cols-2">
 <div style={heroStyle}><div className="inline-flex items-center gap-2 rounded-full border border-teal-200 bg-teal-100 px-3 py-1 text-xs font-semibold text-teal-800 dark:border-teal-900/40 dark:bg-teal-900/30 dark:text-teal-200"><HeartPulse className="h-4 w-4"/>Nurses</div>
 <h1 className="mt-4 text-3xl font-bold tracking-tight text-black dark:text-white sm:text-4xl">Join Doc Chap Ghana as a nurse</h1>
 <p className="mt-4 leading-relaxed text-zinc-700 dark:text-zinc-300">Present your profile, services and availability, and make it easier for patients to find trusted nursing care.</p>
 <div className="mt-5 flex flex-wrap gap-2"><span className="inline-flex items-center gap-2 rounded-full border border-teal-200 bg-teal-100 px-3 py-1 text-xs font-semibold text-teal-800 dark:border-teal-900/40 dark:bg-teal-900/30 dark:text-teal-200"><BadgeCheck className="h-4 w-4"/>Verified profile</span><span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800 dark:border-emerald-900/40 dark:bg-emerald-900/30 dark:text-emerald-200"><Sparkles className="h-4 w-4"/>Professional visibility</span><span className="inline-flex items-center gap-2 rounded-full border border-cyan-200 bg-cyan-100 px-3 py-1 text-xs font-semibold text-cyan-800 dark:border-cyan-900/40 dark:bg-cyan-900/30 dark:text-cyan-200"><CalendarCheck className="h-4 w-4"/>Patient requests</span></div>
 <div className="mt-6 flex flex-col gap-3 sm:flex-row"><button onClick={()=>router.push("/nurses/signup")} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-5 py-3 text-sm font-semibold text-white shadow-md transition hover:bg-teal-500 active:bg-teal-700" style={{animation:"softPulse 2.2s ease-in-out 0.9s infinite"}}>Create my nurse account<ArrowRight className="h-4 w-4"/></button><button onClick={()=>router.push("/nurses/login")} className="inline-flex items-center justify-center gap-2 rounded-xl border border-teal-600 bg-white px-5 py-3 text-sm font-semibold text-teal-700 shadow-md transition hover:bg-teal-50 active:bg-teal-100 dark:border-teal-500 dark:bg-zinc-950 dark:text-white dark:hover:bg-teal-600/20">Log in</button></div>
 <p className="mt-4 text-xs text-zinc-500 dark:text-zinc-400">A clear page to present your services, opening hours and service areas.</p></div>
 <div style={panelStyle} className="relative"><div className="relative overflow-hidden rounded-3xl border border-teal-100 bg-teal-50/70 p-6 shadow-sm dark:border-teal-900/40 dark:bg-teal-950/20"><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-teal-500/12 via-emerald-500/8 to-transparent"/><div className="relative"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-teal-600 shadow-sm"><ShieldCheck className="h-5 w-5 text-white"/></div><div className="min-w-0"><div className="text-sm font-semibold text-black dark:text-white">A clear professional space</div><div className="text-xs text-zinc-600 dark:text-zinc-400">Simpler for nurses, more convenient for patients.</div></div></div>
 <div className="mt-6 grid grid-cols-1 gap-3">
 {[["Present your care","List nursing services such as wound care, injections, home visits, medical assistance and patient support.",ClipboardList,"text-teal-600","from-teal-500/10 to-transparent"],["Home care","Patients can find a nurse by location, available services and care needs.",Home,"text-emerald-600","from-emerald-500/10 to-transparent"],["Appointments & requests","Centralise patient requests and manage your appointments more easily.",CalendarCheck,"text-cyan-700 dark:text-cyan-300","from-cyan-500/10 to-transparent"]].map(([t,d,I,c,g])=>{const Icon=I as React.ElementType; return <div key={t as string} className="relative overflow-hidden rounded-2xl border border-teal-100 bg-white/80 p-4 dark:border-teal-900/40 dark:bg-zinc-950/60"><div className={`pointer-events-none absolute inset-0 bg-gradient-to-br ${g}`}/><div className="relative"><div className="flex items-center gap-3"><Icon className={`h-5 w-5 ${c}`}/><div className="text-sm font-semibold text-black dark:text-white">{t as string}</div></div><p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">{d as string}</p></div></div>})}
 </div><div className="relative mt-6 overflow-hidden rounded-2xl border border-teal-100 bg-white/80 p-4 text-sm text-zinc-700 dark:border-teal-900/40 dark:bg-zinc-950/60 dark:text-zinc-200"><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-teal-500/10 to-transparent"/><div className="relative"><div className="flex items-center gap-2 font-semibold"><Users className="h-4 w-4 text-teal-600"/>Simplified patient relationship</div><p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">Present your experience, service areas, opening hours and contact details.</p></div></div></div></div><div className="pointer-events-none absolute -bottom-6 -right-6 h-32 w-32 rounded-3xl bg-teal-500/10 blur-xl"/></div>
 </div><div className="mt-10 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4"><InfoCard title="Professional profile" description="Present your identity, experience and contact information." icon={UserRound}/><InfoCard title="Care services" description="List your nursing procedures and available services." icon={Stethoscope} delayMs={90} iconBgClass="bg-emerald-600" tintClass="from-emerald-500/12 via-teal-500/8 to-transparent"/><InfoCard title="Patient requests" description="Receive requests and organise care more easily." icon={CalendarCheck} delayMs={180} iconBgClass="bg-cyan-700" tintClass="from-cyan-500/12 via-emerald-500/8 to-transparent"/><InfoCard title="Hours & service areas" description="Show your availability and areas where you provide care." icon={Clock} delayMs={270} iconBgClass="bg-teal-700" tintClass="from-teal-500/12 via-cyan-500/8 to-transparent"/></div></div></section>
 <section className="w-full px-4 py-12 sm:px-6 lg:px-10"><div className="relative overflow-hidden rounded-3xl border border-teal-100 bg-teal-50/70 p-6 shadow-sm dark:border-teal-900/40 dark:bg-teal-950/20 sm:p-8" style={{animation:"fadeUp 900ms cubic-bezier(0.22,1,0.36,1) 240ms both"}}><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-teal-500/10 via-emerald-500/6 to-transparent"/><div className="relative"><h2 className="text-xl font-bold text-black dark:text-white sm:text-2xl">Join Doc Chap Ghana as a nurse</h2><p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400 sm:text-base">Create your nurse workspace to present your activity, services and availability to patients.</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><button onClick={()=>router.push("/nurses/signup")} className="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-600 px-5 py-3 text-sm font-semibold text-white shadow-md transition hover:bg-teal-500">Create a nurse account<ArrowRight className="h-4 w-4"/></button><button onClick={()=>router.push("/nurses/login")} className="inline-flex items-center justify-center gap-2 rounded-xl border border-zinc-300 bg-white px-5 py-3 text-sm font-semibold text-zinc-800 shadow-md transition hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-950 dark:text-white">Log in</button><Link href="/contact" className="inline-flex items-center justify-center gap-2 rounded-xl border border-teal-600 bg-white px-5 py-3 text-sm font-semibold text-teal-700 shadow-md transition hover:bg-teal-50 dark:border-teal-500 dark:bg-zinc-950 dark:text-white">Contact us<LayoutDashboard className="h-4 w-4"/></Link></div></div></div></section>
 </main><Footer/></div>
}