"use client";

import Link from "next/link";
import Image from "next/image";
import { useMemo, useState } from "react";
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import { Stethoscope, ArrowRight, Info, ShieldCheck, Mail, Phone, Lock, Eye, EyeOff, CheckCircle2, BadgeCheck, Sparkles, LineChart } from "lucide-react";

function isStrongPassword(value:string){return /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$/.test(value)}

export default function DoctorSignupPage(){
 const [showPassword,setShowPassword]=useState(false); const [submitted,setSubmitted]=useState(false); const [error,setError]=useState<string|null>(null);
 const heroStyle=useMemo(()=>({animation:"fadeUp 900ms cubic-bezier(0.22,1,0.36,1) 0ms both"}),[]);
 const panelStyle=useMemo(()=>({animation:"fadeUp 900ms cubic-bezier(0.22,1,0.36,1) 120ms both"}),[]);
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError(null);const f=new FormData(e.currentTarget);const password=String(f.get("password")||"");if(!isStrongPassword(password)){setError("Your password must contain at least 8 characters, including one uppercase letter, one lowercase letter, one number and one special character.");return}if(!f.get("privacy")||!f.get("terms")){setError("Please accept the Privacy Policy and Terms of Use.");return}setSubmitted(true)}
 return <div className="min-h-screen bg-zinc-50 dark:bg-black"><Header/><style>{`@keyframes fadeUp{from{opacity:0;transform:translateY(32px)}to{opacity:1;transform:translateY(0)}}@keyframes softPulse{0%{transform:scale(1);opacity:.92}50%{transform:scale(1.02);opacity:1}100%{transform:scale(1);opacity:.92}}`}</style>
 <main><section className="relative overflow-hidden border-b border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-950"><div className="pointer-events-none absolute -top-24 -right-24 h-80 w-80 rounded-full bg-blue-500/20 blur-3xl"/><div className="pointer-events-none absolute -bottom-28 -left-28 h-80 w-80 rounded-full bg-indigo-500/20 blur-3xl"/><div className="pointer-events-none absolute top-1/3 left-1/2 h-64 w-64 -translate-x-1/2 rounded-full bg-sky-500/10 blur-3xl"/>
 <div className="w-full px-4 py-10 sm:px-6 lg:px-10"><div className="grid grid-cols-1 items-center gap-10 lg:grid-cols-2"><div style={heroStyle}><div className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-800 dark:border-blue-900/40 dark:bg-blue-900/20 dark:text-blue-200"><Stethoscope className="h-4 w-4"/>Doctor registration</div><h1 className="mt-4 text-3xl font-bold tracking-tight text-black dark:text-white sm:text-4xl">Create your doctor account</h1><p className="mt-4 leading-relaxed text-zinc-700 dark:text-zinc-300">Join Doc Chap Ghana to grow your practice through appointment management, teleconsultation, patient follow-up and payments on a modern, secure platform.</p>
 <div className="mt-5 flex flex-wrap gap-2"><span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800"><BadgeCheck className="h-4 w-4"/>Secure access</span><span className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-800"><Sparkles className="h-4 w-4"/>Teleconsultation</span><span className="inline-flex items-center gap-2 rounded-full border border-sky-200 bg-sky-50 px-3 py-1 text-xs font-semibold text-sky-800"><LineChart className="h-4 w-4"/>Payments & tracking</span></div>
 <div className="mt-6 flex flex-col gap-3 sm:flex-row"><button onClick={()=>document.getElementById("doctor-signup-form")?.scrollIntoView({behavior:"smooth",block:"start"})} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-md transition hover:bg-blue-500" style={{animation:"softPulse 2.2s ease-in-out .9s infinite"}}>Start registration<ArrowRight className="h-4 w-4"/></button><Link href="/contact" className="inline-flex items-center justify-center gap-2 rounded-xl border border-zinc-300 bg-white px-5 py-3 text-sm font-semibold text-zinc-800 shadow-md transition hover:bg-zinc-50 dark:border-zinc-700 dark:bg-zinc-950 dark:text-white">Need help?<Info className="h-4 w-4"/></Link></div>
 <div className="relative mt-6 overflow-hidden rounded-2xl border border-zinc-200 bg-white p-4 text-sm shadow-sm dark:border-zinc-800 dark:bg-zinc-950"><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-blue-500/10 via-indigo-500/6 to-transparent"/><div className="relative"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4 text-blue-600"/>Why create an account?</div><ul className="mt-3 space-y-2 text-zinc-600 dark:text-zinc-400">{["Open in-person and video consultation slots.","Receive payments and manage invoices.","Centralise patient records, prescriptions and reports.","Apply patient consent and access controls."].map((x,i)=><li key={x} className="flex items-start gap-2"><CheckCircle2 className={`mt-0.5 h-4 w-4 ${["text-emerald-600","text-sky-600","text-indigo-600","text-purple-600"][i]}`}/>{x}</li>)}</ul></div></div>
 <div className="relative mt-4 overflow-hidden rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 shadow-sm"><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-amber-500/10 via-orange-500/5 to-transparent"/><div className="relative"><div className="flex items-center gap-2 font-semibold"><Lock className="h-4 w-4 text-amber-700"/>Password security</div><p className="mt-3 leading-relaxed">Your password must have at least <b>8 characters</b>, including <b>1 uppercase letter</b>, <b>1 lowercase letter</b>, <b>1 number</b> and <b>1 special character</b>.</p></div></div><p className="mt-4 text-xs text-zinc-500">Already have an account? <Link href="/doctors/login" className="underline underline-offset-4">Log in to your doctor space</Link></p></div>
 <div style={panelStyle} className="relative"><div id="doctor-signup-form" className="relative mx-auto w-full max-w-md overflow-hidden rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm dark:border-zinc-800 dark:bg-zinc-950"><div className="pointer-events-none absolute inset-0 bg-gradient-to-br from-blue-500/12 via-indigo-500/8 to-transparent"/><div className="relative"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-600"><ShieldCheck className="h-5 w-5 text-white"/></div><div><div className="text-sm font-semibold text-black dark:text-white">Secure registration</div><div className="text-xs text-zinc-600 dark:text-zinc-400">For doctor accounts only.</div></div></div><div className="mt-5 flex flex-col items-center text-center"><Image src="/images/docchap_pro.png" alt="Doc Chap Pro" width={72} height={72} className="h-16 w-16 object-contain"/><p className="mt-3 text-xs text-zinc-600 dark:text-zinc-400">Create your professional account to manage appointments and grow your practice.</p></div>
 {submitted?<div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><b>Registration received.</b><p className="mt-1">Your Doc Chap Ghana registration will be activated once the Ghana Firebase environment is connected.</p></div>:<form onSubmit={submit} className="mt-6 space-y-4"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{[["Last name","lastName","e.g. Mensah"],["First name","firstName","e.g. Ama"]].map(([l,n,p])=><label key={n} className="space-y-2 text-sm font-medium text-zinc-800 dark:text-zinc-200">{l}<div className="flex items-center gap-2 rounded-xl border border-zinc-200 bg-white/80 px-3 py-2 dark:border-zinc-800 dark:bg-zinc-950/60"><Stethoscope className="h-4 w-4 text-blue-600"/><input name={n} required placeholder={p} className="w-full bg-transparent text-sm outline-none"/></div></label>)}</div>
 <label className="space-y-2 text-sm font-medium text-zinc-800 dark:text-zinc-200">Speciality<div className="flex items-center gap-2 rounded-xl border border-zinc-200 bg-white/80 px-3 py-2 dark:border-zinc-800 dark:bg-zinc-950/60"><Stethoscope className="h-4 w-4 text-sky-600"/><input name="specialty" placeholder="e.g. Cardiology" className="w-full bg-transparent text-sm outline-none"/></div></label>
 <label className="space-y-2 text-sm font-medium text-zinc-800 dark:text-zinc-200">Professional email *<div className="flex items-center gap-2 rounded-xl border border-zinc-200 bg-white/80 px-3 py-2 dark:border-zinc-800 dark:bg-zinc-950/60"><Mail className="h-4 w-4 text-blue-600"/><input name="email" type="email" required placeholder="name@example.com" className="w-full bg-transparent text-sm outline-none"/></div></label>
 <label className="space-y-2 text-sm font-medium text-zinc-800 dark:text-zinc-200">Phone number<div className="flex items-center gap-2 rounded-xl border border-zinc-200 bg-white/80 px-3 py-2 dark:border-zinc-800 dark:bg-zinc-950/60"><Phone className="h-4 w-4 text-emerald-600"/><input name="phone" type="tel" placeholder="+233 ..." className="w-full bg-transparent text-sm outline-none"/></div></label>
 <label className="space-y-2 text-sm font-medium text-zinc-800 dark:text-zinc-200">Password *<div className="flex items-center gap-2 rounded-xl border border-zinc-200 bg-white/80 px-3 py-2 dark:border-zinc-800 dark:bg-zinc-950/60"><Lock className="h-4 w-4 text-indigo-600"/><input name="password" type={showPassword?"text":"password"} required placeholder="Create a strong password" className="w-full bg-transparent text-sm outline-none"/><button type="button" onClick={()=>setShowPassword(!showPassword)} className="text-zinc-500">{showPassword?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>
 <label className="flex items-start gap-2 text-xs text-zinc-600"><input name="privacy" type="checkbox" className="mt-0.5"/>I agree to the <Link href="/privacy" className="underline">Privacy Policy</Link>.</label><label className="flex items-start gap-2 text-xs text-zinc-600"><input name="terms" type="checkbox" className="mt-0.5"/>I agree to the <Link href="/terms-of-use" className="underline">Terms of Use</Link>.</label>{error&&<p className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white shadow-md hover:bg-blue-500">Create my doctor account<ArrowRight className="h-4 w-4"/></button></form>}</div></div></div></div></div></section></main><Footer/></div>
}