"use client";

import React, { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { Timestamp, collection, doc, getDoc, onSnapshot, orderBy, query, where } from "firebase/firestore";
import { AlertCircle, ArrowRight, BadgeCheck, CalendarCheck2, CalendarDays, CheckCircle2, Clock3, CreditCard, Loader2, MapPin, Search, ShieldCheck, Smartphone, Stethoscope, UserRound, Video } from "lucide-react";

import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";
import DoctorSidebar from "@/app/components/DoctorSidebar";
import { auth, db } from "@/lib/firebase/client";

type AppointmentMode = "in_person" | "video" | "phone";
type AppointmentStatus = "ongoing" | "upcoming" | "completed" | "cancelled";

type Appointment = {
  id: string;
  patientName: string;
  reason: string;
  startAt: Date;
  endAt: Date;
  mode: AppointmentMode;
  status: AppointmentStatus;
  paid: boolean;
  amount: number;
  currency: string;
};

function s(v: unknown) { return (v ?? "").toString().trim(); }
function o(v: unknown): Record<string, any> { return v && typeof v === "object" && !Array.isArray(v) ? v as Record<string, any> : {}; }
function d(v: unknown): Date | null {
  if (v instanceof Timestamp) return v.toDate();
  if (v instanceof Date) return v;
  if (typeof v === "string" || typeof v === "number") { const x = new Date(v); return Number.isNaN(x.getTime()) ? null : x; }
  if (v && typeof v === "object" && "toDate" in (v as any) && typeof (v as any).toDate === "function") { try { return (v as any).toDate(); } catch { return null; } }
  return null;
}
function n(v: unknown) { if (typeof v === "number" && Number.isFinite(v)) return v; if (typeof v === "string") { const x = Number(v.replace(/[^0-9.,-]/g, "").replace(",", ".")); return Number.isFinite(x) ? x : 0; } return 0; }
function money(amount: number, currency = "GHS") { try { return new Intl.NumberFormat("en-GH", { style: "currency", currency: s(currency).toUpperCase() || "GHS", maximumFractionDigits: 2 }).format(amount); } catch { return `${amount.toFixed(2)} ${currency}`; } }
function time(date: Date) { return new Intl.DateTimeFormat("en-GH", { hour: "2-digit", minute: "2-digit", hour12: false }).format(date); }
function dayStart(date: Date) { return new Date(date.getFullYear(), date.getMonth(), date.getDate()); }
function dayEnd(date: Date) { return new Date(date.getFullYear(), date.getMonth(), date.getDate() + 1); }
function mode(data: Record<string, any>): AppointmentMode { const raw = `${s(data.appointmentType)} ${s(data.type)} ${s(data.mode)}`.toLowerCase(); if (raw.includes("phone") || raw.includes("call")) return "phone"; if (raw.includes("tele") || raw.includes("video") || raw.includes("visio")) return "video"; return "in_person"; }
function status(data: Record<string, any>, start: Date, end: Date): AppointmentStatus { const raw = s(data.status).toLowerCase(); if (["cancelled","canceled","cancelled_by_patient","cancelled_by_doctor"].includes(raw)) return "cancelled"; if (["completed","complete","finished","done"].includes(raw)) return "completed"; const now = new Date(); if (now >= start && now < end) return "ongoing"; if (now >= end) return "completed"; return "upcoming"; }
function mapAppointment(id: string, raw: unknown): Appointment | null {
  const data = o(raw); const startAt = d(data.startAt) || d(data.appointmentDate) || d(data.date); if (!startAt) return null;
  const duration = Number(data.durationMinutes) > 0 ? Number(data.durationMinutes) : 30; const endAt = new Date(startAt.getTime() + duration * 60000); const patient = o(data.patientSummary); const payment = o(data.payment); const paymentStatus = `${s(data.paymentStatus)} ${s(payment.status)}`.toLowerCase();
  return { id, patientName: s(data.patientName) || s(data.patientDisplayName) || s(patient.displayName) || s(patient.fullName) || "Patient", reason: s(data.reason) || s(data.motif) || "Consultation", startAt, endAt, mode: mode(data), status: status(data,startAt,endAt), paid: ["paid","success","succeeded","completed"].some(x => paymentStatus.includes(x)) || Boolean(payment.paidAt), amount: n(payment.netAmount) || n(payment.amount) || n(data.amount) || n(data.consultationFee), currency: s(payment.currency).toUpperCase() || s(data.currency).toUpperCase() || "GHS" };
}
function doctorView(raw: unknown) { const data = o(raw); const p=o(data.profile); const pro=o(data.professional); const first=s(p.firstName); const name=s(p.displayName)||s(p.fullName)||`${first} ${s(p.lastName)}`.trim()||"Doctor"; const verificationStatus=s(pro.verificationStatus).toLowerCase()||"pending"; return { name, firstName:first||name.split(" ")[0]||"Doctor", specialty:s(pro.specialty)||s(p.specialty)||"Medical professional", city:s(p.city)||s(p.region)||"Ghana", verified:pro.verified===true||verificationStatus==="verified"||verificationStatus==="approved", verificationStatus }; }
function modeMeta(value: AppointmentMode) { if (value === "video") return { label:"Video", icon:Video, cls:"border-violet-200 bg-violet-50 text-violet-700" }; if (value === "phone") return { label:"Phone", icon:Smartphone, cls:"border-emerald-200 bg-emerald-50 text-emerald-700" }; return { label:"In person", icon:UserRound, cls:"border-cyan-200 bg-cyan-50 text-cyan-700" }; }
function statusCls(value: AppointmentStatus) { if (value === "ongoing") return "border-emerald-200 bg-emerald-50 text-emerald-700"; if (value === "upcoming") return "border-blue-200 bg-blue-50 text-blue-700"; if (value === "cancelled") return "border-red-200 bg-red-50 text-red-700"; return "border-zinc-200 bg-zinc-50 text-zinc-600"; }

export default function ScheduleClient() {
  const router = useRouter();
  const [loading,setLoading]=useState(true); const [uid,setUid]=useState<string|null>(null); const [doctorData,setDoctorData]=useState<any>(null); const [appointments,setAppointments]=useState<Appointment[]>([]); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState("");

  useEffect(()=>{ const a=auth, f=db; if(!a||!f){setError("Firebase is not initialized.");setLoading(false);return;} const ua=onAuthStateChanged(a,async user=>{ if(!user?.uid){router.replace("/doctors/login");return;} try{ const snap=await getDoc(doc(f,"professionals",user.uid)); if(!snap.exists()){await signOut(a);router.replace("/doctors/login");return;} const data=snap.data(); const pro=o(data.professional); const type=s(data.professionalType||pro.type||data.role).toLowerCase(); if((type&&type!=="doctor")||data.active===false){await signOut(a);router.replace("/doctors/login");return;} setUid(user.uid);setDoctorData(data);setError(null);}catch(e){console.error(e);setError("Unable to verify your doctor account.");}finally{setLoading(false);} }); return()=>ua();},[router]);
  useEffect(()=>{const f=db;if(!f||!uid)return;const u=onSnapshot(doc(f,"professionals",uid),snap=>{if(snap.exists())setDoctorData(snap.data());});return()=>u();},[uid]);
  useEffect(()=>{const f=db;if(!f||!uid)return;const now=new Date();const q=query(collection(f,"professionals",uid,"appointments"),where("startAt",">=",Timestamp.fromDate(dayStart(now))),where("startAt","<",Timestamp.fromDate(dayEnd(now))),orderBy("startAt","asc"));const u=onSnapshot(q,snap=>setAppointments(snap.docs.map(x=>mapAppointment(x.id,x.data())).filter((x):x is Appointment=>x!==null)),e=>{console.error(e);setAppointments([]);});return()=>u();},[uid]);

  const doctor=useMemo(()=>doctorView(doctorData||{}),[doctorData]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return !q?appointments:appointments.filter(x=>x.patientName.toLowerCase().includes(q)||x.reason.toLowerCase().includes(q)||time(x.startAt).includes(q));},[appointments,search]);
  const upcoming=appointments.filter(x=>x.status==="upcoming"||x.status==="ongoing").length; const video=appointments.filter(x=>x.mode==="video").length; const phone=appointments.filter(x=>x.mode==="phone").length; const revenue=appointments.filter(x=>x.paid).reduce((t,x)=>t+x.amount,0);
  const availability=o(doctorData?.availability); const week=o(availability.week); const todayKey=["sun","mon","tue","wed","thu","fri","sat"][new Date().getDay()]; const today=o(week[todayKey]); const config=o(doctorData?.configuration);

  if(loading)return <div className="min-h-screen bg-[#f6f8fc] dark:bg-black"><DoctorSidebar/><div className="lg:pl-72"><Header/><main className="flex min-h-[75vh] items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-blue-600"/></main></div></div>;

  return <div className="min-h-screen bg-[#f6f8fc] dark:bg-black"><DoctorSidebar/><div className="lg:pl-72"><Header/><main>
    <section className="relative overflow-hidden border-b border-blue-950/20 bg-gradient-to-br from-[#06172f] via-[#0a2d5d] to-[#1767b5] text-white"><div className="pointer-events-none absolute -right-24 -top-28 h-96 w-96 rounded-full bg-cyan-400/20 blur-3xl"/><div className="pointer-events-none absolute -bottom-32 left-1/3 h-80 w-80 rounded-full bg-violet-500/20 blur-3xl"/><div className="relative px-4 py-8 sm:px-6 sm:py-10 lg:px-10"><div className="flex flex-col gap-7 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-3xl"><div className="flex flex-wrap items-center gap-2"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-semibold"><CalendarDays className="h-4 w-4 text-cyan-300"/>Doctor schedule</span>{doctor.verified?<span className="inline-flex items-center gap-2 rounded-full border border-emerald-300/30 bg-emerald-400/15 px-3 py-1.5 text-xs font-semibold text-emerald-100"><BadgeCheck className="h-4 w-4"/>Verified doctor</span>:<span className="inline-flex items-center gap-2 rounded-full border border-amber-300/30 bg-amber-400/15 px-3 py-1.5 text-xs font-semibold text-amber-100"><ShieldCheck className="h-4 w-4"/>Verification {doctor.verificationStatus}</span>}</div><h1 className="mt-5 text-3xl font-black sm:text-4xl">Today&apos;s schedule</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-blue-100">Welcome, {doctor.name}. Review today&apos;s appointments and your current consultation availability.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs font-semibold">{doctor.specialty}</span><span className="inline-flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-xs font-semibold"><MapPin className="h-4 w-4 text-emerald-300"/>{doctor.city}</span></div></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/doctors/dashboard/appointments" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-white/20 bg-white/10 px-5 py-3 text-sm font-semibold">All appointments<ArrowRight className="h-4 w-4"/></Link><Link href="/doctors/dashboard/configuration" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-bold text-[#071b3a]">Availability settings<Clock3 className="h-4 w-4"/></Link></div></div></div></section>
    <section className="px-4 py-7 sm:px-6 lg:px-10">{error&&<div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertCircle className="mr-2 inline h-4 w-4"/>{error}</div>}<div className="grid grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1.55fr)_360px]"><div className="space-y-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Today",appointments.length,CalendarCheck2,"bg-blue-600"],["Upcoming",upcoming,Clock3,"bg-indigo-600"],["Video",video,Video,"bg-violet-600"],["Phone",phone,Smartphone,"bg-emerald-600"]].map(([label,value,Icon,cls])=>{const C=Icon as React.ElementType;return <div key={String(label)} className="rounded-2xl border border-zinc-200 bg-white p-4 shadow-sm dark:border-zinc-800 dark:bg-zinc-950"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${cls}`}><C className="h-5 w-5 text-white"/></div><div className="mt-3 text-2xl font-black text-zinc-950 dark:text-white">{String(value)}</div><div className="mt-1 text-xs text-zinc-500">{String(label)}</div></div>})}</div>
      <div className="rounded-[28px] border border-zinc-200 bg-white p-5 shadow-sm sm:p-6 dark:border-zinc-800 dark:bg-zinc-950"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-black text-zinc-950 dark:text-white">Today&apos;s appointments</h2><p className="mt-1 text-xs text-zinc-500">Your consultations scheduled for today.</p></div><div className="relative w-full sm:max-w-xs"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..." className="h-11 w-full rounded-2xl border border-zinc-200 bg-zinc-50 pl-10 pr-4 text-sm outline-none dark:border-zinc-800 dark:bg-zinc-900 dark:text-white"/></div></div>{filtered.length===0?<div className="mt-6 rounded-2xl border border-dashed border-zinc-300 p-10 text-center dark:border-zinc-700"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-500"/><div className="mt-3 text-sm font-bold text-zinc-900 dark:text-white">No appointments found</div></div>:<div className="mt-6 space-y-3">{filtered.map(x=>{const m=modeMeta(x.mode);const I=m.icon;return <button key={x.id} onClick={()=>router.push(`/doctors/dashboard/appointments/${x.id}`)} className="w-full rounded-2xl border border-zinc-200 p-4 text-left transition hover:border-blue-200 hover:bg-blue-50/40 dark:border-zinc-800 dark:bg-zinc-950"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-black text-zinc-950 dark:text-white">{x.patientName}</span><span className={`rounded-full border px-2.5 py-1 text-[11px] font-bold capitalize ${statusCls(x.status)}`}>{x.status}</span></div><p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">{x.reason}</p><div className="mt-2 text-xs text-zinc-500">{time(x.startAt)} - {time(x.endAt)}</div></div><div className="flex flex-wrap gap-2"><span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-bold ${m.cls}`}><I className="h-3.5 w-3.5"/>{m.label}</span><span className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${x.paid?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-amber-200 bg-amber-50 text-amber-700"}`}>{x.paid?"Paid":"Unpaid"}</span></div></div></button>})}</div>}</div></div>
      <aside className="space-y-5"><div className="overflow-hidden rounded-[28px] border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-zinc-950"><div className="bg-gradient-to-br from-blue-600 to-indigo-700 p-5 text-white"><Clock3 className="h-7 w-7"/><h3 className="mt-4 text-lg font-black">Today&apos;s availability</h3></div><div className="p-5"><div className="flex items-center justify-between rounded-2xl bg-zinc-50 p-4 dark:bg-zinc-900"><span className="text-sm font-semibold">Status</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${today.open===true?"bg-emerald-100 text-emerald-700":"bg-zinc-200 text-zinc-600"}`}>{today.open===true?"Open":"Closed"}</span></div><div className="mt-3 rounded-2xl bg-zinc-50 p-4 dark:bg-zinc-900"><div className="text-xs text-zinc-500">Consultation hours</div><div className="mt-1 text-base font-black dark:text-white">{today.open===true?`${s(today.start)||"09:00"} – ${s(today.end)||"17:00"}`:"Not available today"}</div></div><Link href="/doctors/dashboard/configuration" className="mt-4 flex items-center justify-center gap-2 rounded-2xl bg-blue-600 px-4 py-3 text-sm font-bold text-white">Manage availability<ArrowRight className="h-4 w-4"/></Link></div></div><div className="rounded-[28px] border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-zinc-950"><h3 className="text-sm font-black dark:text-white">Consultation modes</h3><div className="mt-4 space-y-3">{[["In-person",config.inPersonEnabled!==false,UserRound],["Video",config.teleconsultationEnabled!==false,Video],["Phone",config.phoneConsultationEnabled===true,Smartphone]].map(([label,enabled,Icon])=>{const C=Icon as React.ElementType;return <div key={String(label)} className="flex items-center gap-3 rounded-2xl border border-zinc-200 p-3 dark:border-zinc-800"><C className="h-4 w-4 text-blue-600"/><span className="flex-1 text-xs font-semibold dark:text-zinc-300">{String(label)}</span><span className={`h-2.5 w-2.5 rounded-full ${enabled?"bg-emerald-500":"bg-zinc-300"}`}/></div>})}</div></div><div className="rounded-[28px] border border-emerald-200 bg-emerald-50/70 p-5 dark:border-emerald-900/40 dark:bg-emerald-950/20"><CreditCard className="h-6 w-6 text-emerald-700"/><div className="mt-3 text-sm font-black dark:text-white">Today&apos;s paid revenue</div><div className="mt-2 text-2xl font-black text-emerald-700 dark:text-emerald-300">{money(revenue,appointments[0]?.currency||"GHS")}</div></div></aside></div></section>
  </main><Footer/></div></div>;
}